config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  } do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
  resources :orders do
    member do
      get 'orderdetail'
    end
  end
  resources :data_entries
  resources :user_agrovets
  resources :agrovets do
    resources :orders, only: [:index, :show, :new, :create]
    member do
      get 'agrovetinfo'
      get 'placeorder'
      get 'allorders'
    end
    get 'data_entries/new'
    get 'orders/new'
  end
  resources :products
  # devise_for :users
  root "pages#home"
  get 'products/index'
  get 'agrovets/index'
  get 'admin', to: 'pages#admin', as: 'pages_admin'
  get 'salesrep', to: 'pages#salesrep', as: 'pages_salesrep'
  get 'manager', to: 'pages#manager', as: 'pages_manager'
  get 'pendingorders', to: 'pages#pendingorders', as: 'pages_pendingorders'
  get 'dispatchedorders', to: 'pages#dispatchedorders', as: 'pages_dispatchedorders'
  get 'receivedorders', to: 'pages#receivedorders', as: 'pages_receivedorders'
  get 'allsalesreps', to: 'pages#allsalesreps', as: 'pages_allsalesreps'
  get 'allagrovets', to: 'pages#allagrovets', as: 'pages_allagrovets'
end

app/models/agrovet.rb
class Agrovet < ApplicationRecord
  belongs_to :user
  has_many :data_entries
  has_many :products
  has_many :orders

  validates :name, presence: true
  validates :location, presence: true
  validates :owner_name, presence: true
  validates :owner_phone, presence: true
  validates :owner_email, presence: true
  validates :user_id, presence: true

  # def self.search(search)
  #   if search
  #     where(["name LIKE ?","%#{search}%"])
  #   else
  #     all
  #   end
  # end
  # Method to retrieve the latest form entry for the agrovet
  # def all_latest_data_entry
  #   @data_entries.order(created_at: :desc).first
  # end
  # def all_latest_product_1_data_entry_total
  #   (@products.first&.price || 0) * (@all_latest_data_entry&.product_1_quantity || 0)
  # end
  # def all_latest_product_2_data_entry_total
  #   (@products.second&.price || 0) * (@all_latest_data_entry&.product_2_quantity || 0)
  # end
  # def all_latest_product_3_data_entry_total
  #   (@products.third&.price || 0) * (@all_latest_data_entry&.product_3_quantity || 0)
  # end
  # def all_latest_product_4_data_entry_total
  #   (@products.fourth&.price || 0) * (@all_latest_data_entry&.product_4_quantity || 0)
  # end

  # def all_latest_total_data_entry_amount
  #   @all_latest_product_1_data_entry_total + @all_latest_product_2_data_entry_total + @all_latest_product_3_data_entry_total + @all_latest_product_4_data_entry_total
  # end
end

app/controllers/agrovets_controller.rb
class AgrovetsController < ApplicationController
  before_action :set_agrovet, only: %i[show edit update destroy]

  # GET /agrovets or /agrovets.json
  def index
    @agrovets = Agrovet.all
    @agrovets_count = Agrovet.count
  end

  # GET /agrovets/1 or /agrovets/1.json
  def show
  end

  # GET /agrovets/new
  def new
    @agrovet = current_user.agrovets.build
  end

  # GET /agrovets/1/edit
  def edit
  end

  # POST /agrovets or /agrovets.json
  def create
    @agrovet = Agrovet.new(agrovet_params)

    respond_to do |format|
      if @agrovet.save
        format.html { redirect_to pages_salesrep_path, notice: "Agrovet was successfully created." }
        format.json { render :show, status: :created, location: @agrovet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @agrovet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agrovets/1 or /agrovets/1.json
  def update
    respond_to do |format|
      if @agrovet.update(agrovet_params)
        format.html { redirect_to agrovet_url(@agrovet), notice: "Agrovet was successfully updated." }
        format.json { render :show, status: :ok, location: @agrovet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @agrovet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agrovets/1 or /agrovets/1.json
  def destroy
    @agrovet.destroy

    respond_to do |format|
      format.html { redirect_to agrovets_url, notice: "Agrovet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def agrovetinfo
    @agrovet = Agrovet.find(params[:id])
    @latest_data_entry = @agrovet.data_entries.order(created_at: :desc).first
    @products = Product.limit(7)
    @latest_product_1_data_entry_total = (@products.first&.price || 0) * (@latest_data_entry&.product_1_quantity || 0)
    @latest_product_2_data_entry_total = (@products.second&.price || 0) * (@latest_data_entry&.product_2_quantity || 0)
    @latest_product_3_data_entry_total = (@products.third&.price || 0) * (@latest_data_entry&.product_3_quantity || 0)
    @latest_product_4_data_entry_total = (@products.fourth&.price || 0) * (@latest_data_entry&.product_4_quantity || 0)
    @latest_total_data_entry_amount = @latest_product_1_data_entry_total + @latest_product_2_data_entry_total + @latest_product_3_data_entry_total + @latest_product_4_data_entry_total
  end

  def placeorder
    @agrovet = Agrovet.find(params[:id])
    @products = Product.limit(7)
    @latest_order = @agrovet.orders.order(created_at: :desc).first
    @latest_product_1_order_total = (@products.first&.price || 0) * (@latest_order&.product_1_quantity || 0)
    @latest_product_2_order_total = (@products.second&.price || 0) * (@latest_order&.product_2_quantity || 0)
    @latest_product_3_order_total = (@products.third&.price || 0) * (@latest_order&.product_3_quantity || 0)
    @latest_product_4_order_total = (@products.fourth&.price || 0) * (@latest_order&.product_4_quantity || 0)
    @latest_total_order_amount = @latest_product_1_order_total + @latest_product_2_order_total + @latest_product_3_order_total + @latest_product_4_order_total
  end

  def allorders
    @agrovet = Agrovet.find(params[:id])
    @orders = @agrovet.orders
  end

  def orderdetail
    @agrovet = Agrovet.find(params[:id])
    @orders = @agrovet.orders
    # @order = Order.find(params[:id])
    @order = @orders.find(params[:order_id])
    @products = Product.all
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_agrovet
    @agrovet = Agrovet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def agrovet_params
    params.require(:agrovet).permit(:name, :location, :owner_name, :owner_phone, :owner_email, :user_id)
  end
end

app/helpers/agrovets_helper.rb
module AgrovetsHelper
end

app/views/agrovets/_agrovet.html.erb
<div id="<%= dom_id agrovet %>">
  <p>
    <strong>Name:</strong>
    <%= agrovet.name %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= agrovet.location %>
  </p>

  <p>
    <strong>Owner name:</strong>
    <%= agrovet.owner_name %>
  </p>

  <p>
    <strong>Owner phone:</strong>
    <%= agrovet.owner_phone %>
  </p>

  <p>
    <strong>Owner email:</strong>
    <%= agrovet.owner_email %>
  </p>


</div>

app/views/agrovets/_agrovet_links.html.erb
<% @agrovets.each do |agrovet| %>
  <%= link_to "Agrovet #{agrovet.name}", agrovetinfo_path(agrovet) %>
<% end %>

app/views/agrovets/_form.html.erb
<%= form_with(model: agrovet, local: true, class: "my-4") do |f| %>
  <div class="row">
    <div class="col-md-6">
      <% if agrovet.errors.any? %>
        <div class="alert alert-danger">
          <h2><%= pluralize(agrovet.errors.count, "error") %> prohibited this agrovet from being saved:</h2>
          <ul>
            <% agrovet.errors.full_messages.each do |error| %>
              <li><%= error %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-3">
        <%= f.label :name, class: "form-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= f.label :location, class: "form-label" %>
        <%= f.text_field :location, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= f.label :owner_name, class: "form-label" %>
        <%= f.text_field :owner_name, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= f.label :owner_phone, class: "form-label" %>
        <%= f.number_field :owner_phone, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= f.label :owner_email, class: "form-label" %>
        <%= f.text_field :owner_email, class: "form-control" %>
      </div>
    </div>

    
      <div class="mb-3">
        <%= f.hidden_field :user_id, value: @agrovet.user_id, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= f.submit "Save", class: "btn btn-danger btn-lg" %>
      </div>
    
  </div>
</div>
<% end %>

app/views/agrovets/agrovetinfo.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto text-center">
      <h5><%= current_user.firstname %></h5>
      <h3><%= @agrovet.name %></h3>
      <p><strong>Owner's Phone: </strong>0<%= @agrovet.owner_phone %></p>
      <p><strong>Owner's Name: </strong><%= @agrovet.owner_name %></p>
      <p><strong>Location: </strong><%= @agrovet.location %></p>

      <% if @latest_data_entry.present? %>
        <!-- Display information from the latest form entry here -->
        <p class="entry-date"><strong>Entry Date:</strong> <%= @latest_data_entry.created_at.strftime("%d-%m-%Y at %H:%M:%S") %></p>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Product</th>
              <th>Quantity</th>
              <th>Amount</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @products.first.name %></td>
              <td><%= (@latest_data_entry&.product_1_quantity || 0) %></td>
              <td><%= @latest_product_1_data_entry_total %></td>
            </tr>
            <tr>
              <td><%= @products.second.name %></td>
              <td><%= (@latest_data_entry&.product_2_quantity || 0) %></td>
              <td><%= @latest_product_2_data_entry_total %></td>
            </tr>
            <tr>
              <td><%= @products.third.name %></td>
              <td><%= (@latest_data_entry&.product_3_quantity || 0) %></td>
              <td><%= @latest_product_1_data_entry_total %></td>
            </tr>
            <tr>
              <td><%= @products.fourth.name %></td>
              <td><%= (@latest_data_entry&.product_4_quantity || 0) %></td>
              <td><%= @latest_product_1_data_entry_total %></td>
            </tr>
          </tbody>
        </table>
        <p><strong>Total Amount:</strong> Ksh.<%= @latest_total_data_entry_amount %></p>
        <p><strong>Money Paid Today:</strong> Ksh.<%= @latest_data_entry.money_paid %></p>
        <p><strong>Money Owed Today:</strong> Ksh.<%= @latest_data_entry.money_owed %></p>
        <%= link_to "Orders", placeorder_agrovet_path(@agrovet), class: "btn btn-success" %>
        <%= link_to "Update Agrovet Info", new_data_entry_path(agrovet_id: @agrovet.id), class: "btn btn-success" %>
        <!-- Add more information from the form entry as needed -->
      <% else %>
        <p>No form entries available for this agrovet.</p>
        <%= link_to "Place Order", new_order_path(agrovet_id: @agrovet.id), class: "btn btn-success" %>
        <%= link_to "Create Form Entry", new_data_entry_path(agrovet_id: @agrovet.id), class: "btn btn-success" %>
      <% end %>

      <button type="button" class="btn btn-sales-rep-home mt-4" style="background: brown;">
        <%= link_to "Sales Rep Home", pages_salesrep_path, style: "color: #fff; text-decoration: none; font-weight: bold;" %>
      </button>
    </div>
  </div>
</div>

app/views/agrovets/allorders.html.erb
<% if @orders.any? %>
  <h4 class="mb-4">All Orders for <%= @agrovet.name %></h4>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Order Date</th>
        <th>Order Number</th>
        <th>Status</th>
        <th>Details</th>
        <!-- Add more table headers as needed -->
      </tr>
    </thead>
    <tbody>
      <% @orders.order(created_at: :desc).each do |order| %>
        <tr>
          <td><%= order.created_at.to_time.in_time_zone %></td>
          <td><%= order.id %></td>
          <td><%= order.status %></td>
          <td>
            <%= link_to "View Details", order_path(order), class: "btn btn-success btn-sm" %> 
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "Go Back to Place Order", placeorder_agrovet_path(@agrovet), class: "btn btn-success" %>

<% else %>
  <p>No orders available for this agrovet.</p>
<% end %>

app/views/agrovets/edit.html.erb
<h1>Editing agrovet</h1>

<%= render "form", agrovet: @agrovet %>

<br>

<div>
  <%= link_to "Show this agrovet", @agrovet %> |
  <%= link_to "Back to agrovets", agrovets_path %>
</div>

app/views/agrovets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Agrovets</h1>

<div id="agrovets">
  <% @agrovets.each do |agrovet| %>
    <%= render agrovet %>
    <p>
      <%= link_to "Show this agrovet", agrovet %>
    </p>
  <% end %>
</div>

<%= link_to "New agrovet", new_agrovet_path %>

app/views/agrovets/new.html.erb
<h1>New agrovet</h1>

<%= render "form", agrovet: @agrovet %>

<br>

<div>
  <%# <%= link_to "Back to agrovets", agrovets_path %> 
</div>

app/views/agrovets/orderdetail.html.erb
<div id="<%= dom_id(order) %>">
  <p>
    <strong>Agrovet:</strong>
    <%= order.agrovet_id %>
  </p>

  <p>
    <strong>Order number:</strong>
    <%= order.id %>
  </p>

  <p>
    <strong><%= @products.first.name %>:</strong>
    <%= order.product_1_quantity %>
  </p>

  <p>
    <strong><%= @products.second.name %>:</strong>
    <%= order.product_2_quantity %>
  </p>

  <p>
    <strong><%= @products.third.name %>:</strong>
    <%= order.product_3_quantity %>
  </p>

  <p>
    <strong><%= @products.fourth.name %>:</strong>
    <%= order.product_4_quantity %>
  </p>

  <p>
    <strong>Total amount:</strong>
    <%= order.total_amount %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= order.status %>
  </p>

  <p>
    <strong>Created at:</strong>
    <%= order.created_at %>
  </p>
</div>

app/views/agrovets/placeorder.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto text-center">
      <h5>Welcome, <%= current_user.firstname %></h5>
      <h3><%= @agrovet.name %></h3>
      <p><strong>Owner's Phone: </strong>0<%= @agrovet.owner_phone %></p>
      <p><strong>Owner's Name: </strong><%= @agrovet.owner_name %></p>
      <p><strong>Location: </strong><%= @agrovet.location %></p>

      <% if @latest_order.present? %>
        <!-- Display information from the latest order here -->
        <p class="order-date"><strong>Order Date:</strong> <%= @latest_order.created_at.strftime("%d-%m-%Y at %H:%M:%S") %></p>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Product</th>
              <th>Quantity</th>
              <th>Amount</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @products.first.name %></td>
              <td><%= @latest_order.product_1_quantity %></td>
              <td><%= @latest_product_1_order_total %></td>
            </tr>
            <tr>
              <td><%= @products.second.name %></td>
              <td><%= @latest_order.product_2_quantity %></td>
              <td><%= @latest_product_2_order_total %></td>
            </tr>
            <tr>
                <td><%= @products.third.name %></td>
                <td><%= @latest_order.product_3_quantity %></td>
                <td><%= @latest_product_3_order_total %></td>
            </tr>
            <tr>
                <td><%= @products.fourth.name %></td>
                <td><%= @latest_order.product_4_quantity %></td>
                <td><%= @latest_product_4_order_total %></td>
            </tr>
            </tbody>
        </table>
        <p><strong>Total Amount:</strong> Ksh.<%= @latest_total_order_amount %></p>
        <p><strong>Status:</strong> <%= @latest_order.status %></p>
        <p><strong>Order Number:</strong> <%= @latest_order.id %></p>
        <% if @latest_order.status != 'Received' %>
            <%= link_to "Update Order", edit_order_path(@latest_order), class: "btn btn-success" %>
        <% end %>
        <%= link_to "Place Order", new_order_path(agrovet_id: @agrovet.id), class: "btn btn-success" %>
        <%= link_to "View All Orders", allorders_agrovet_path(@agrovet), class: "btn btn-success" %><br>
        <button type="button" class="btn btn-sales-rep-home mt-4" style="background: brown;">
        <%= link_to "Go Back", agrovetinfo_agrovet_path(@agrovet.id), style: "color: #fff; text-decoration: none; font-weight: bold;" %>
      </button>
        <% else %>
        <p>No Orders available for this agrovet.</p>
        <%= link_to "Place Order", new_order_path(agrovet_id: @agrovet.id), class: "btn btn-success" %>
        <% end %>
    </div>
    </div>
</div>

app/views/agrovets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @agrovet %>

<div>
  <%= link_to "Edit this agrovet", edit_agrovet_path(@agrovet) %> |
  <%= link_to "Back to agrovets", agrovets_path %>

  <%= button_to "Destroy this agrovet", @agrovet, method: :delete %>
</div>