config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  } do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
  resources :orders do
    member do
      get 'orderdetail'
    end
  end
  resources :data_entries
  resources :user_agrovets
  resources :agrovets do
    resources :orders, only: [:index, :show, :new, :create]
    member do
      get 'agrovetinfo'
      get 'placeorder'
      get 'allorders'
    end
    get 'data_entries/new'
    get 'orders/new'
  end
  resources :products
  # devise_for :users
  root "pages#home"
  get 'products/index'
  get 'agrovets/index'
  get 'admin', to: 'pages#admin', as: 'pages_admin'
  get 'salesrep', to: 'pages#salesrep', as: 'pages_salesrep'
  get 'manager', to: 'pages#manager', as: 'pages_manager'
  get 'pendingorders', to: 'pages#pendingorders', as: 'pages_pendingorders'
  get 'dispatchedorders', to: 'pages#dispatchedorders', as: 'pages_dispatchedorders'
  get 'receivedorders', to: 'pages#receivedorders', as: 'pages_receivedorders'
  get 'allsalesreps', to: 'pages#allsalesreps', as: 'pages_allsalesreps'
  get 'allagrovets', to: 'pages#allagrovets', as: 'pages_allagrovets'
end

app/models/user_agrovet.rb
class UserAgrovet < ApplicationRecord
  belongs_to :user
  belongs_to :agrovet
end

app/controllers/user_agrovets_controller.rb
class UserAgrovetsController < ApplicationController
  before_action :set_user_agrovet, only: %i[show edit update destroy]

  # GET /user_agrovets or /user_agrovets.json
  def index
    @user_agrovets = UserAgrovet.all
  end

  # GET /user_agrovets/1 or /user_agrovets/1.json
  def show
  end

  # GET /user_agrovets/new
  def new
    @user_agrovet = UserAgrovet.new
  end

  # GET /user_agrovets/1/edit
  def edit
  end

  # POST /user_agrovets or /user_agrovets.json
  def create
    @user_agrovet = UserAgrovet.new(user_agrovet_params)

    respond_to do |format|
      if @user_agrovet.save
        format.html { redirect_to user_agrovet_url(@user_agrovet), notice: "User agrovet was successfully created." }
        format.json { render :show, status: :created, location: @user_agrovet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_agrovet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_agrovets/1 or /user_agrovets/1.json
  def update
    respond_to do |format|
      if @user_agrovet.update(user_agrovet_params)
        format.html { redirect_to user_agrovet_url(@user_agrovet), notice: "User agrovet was successfully updated." }
        format.json { render :show, status: :ok, location: @user_agrovet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_agrovet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_agrovets/1 or /user_agrovets/1.json
  def destroy
    @user_agrovet.destroy

    respond_to do |format|
      format.html { redirect_to user_agrovets_url, notice: "User agrovet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_agrovet
    @user_agrovet = UserAgrovet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_agrovet_params
    params.require(:user_agrovet).permit(:user_id, :agrovet_id)
  end
end

app/helpers/user_agrovets_helper.rb
module UserAgrovetsHelper
end

app/views/user_agrovets/_form.html.erb
<%= form_with(model: user_agrovet) do |form| %>
  <% if user_agrovet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_agrovet.errors.count, "error") %> prohibited this user_agrovet from being saved:</h2>

      <ul>
        <% user_agrovet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :agrovet_id, style: "display: block" %>
    <%= form.text_field :agrovet_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/user_agrovets/_user_agrovet.html.erb
<div id="<%= dom_id user_agrovet %>">
  <p>
    <strong>User:</strong>
    <%= user_agrovet.user_id %>
  </p>

  <p>
    <strong>Agrovet:</strong>
    <%= user_agrovet.agrovet_id %>
  </p>

</div>

app/views/user_agrovets/edit.html.erb
<h1>Editing user agrovet</h1>

<%= render "form", user_agrovet: @user_agrovet %>

<br>

<div>
  <%= link_to "Show this user agrovet", @user_agrovet %> |
  <%= link_to "Back to user agrovets", user_agrovets_path %>
</div>

app/views/user_agrovets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User agrovets</h1>

<div id="user_agrovets">
  <% @user_agrovets.each do |user_agrovet| %>
    <%= render user_agrovet %>
    <p>
      <%= link_to "Show this user agrovet", user_agrovet %>
    </p>
  <% end %>
</div>

<%= link_to "New user agrovet", new_user_agrovet_path %>

app/views/user_agrovets/new.html.erb
<h1>New user agrovet</h1>

<%= render "form", user_agrovet: @user_agrovet %>

<br>

<div>
  <%= link_to "Back to user agrovets", user_agrovets_path %>
</div>

app/views/user_agrovets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_agrovet %>

<div>
  <%= link_to "Edit this user agrovet", edit_user_agrovet_path(@user_agrovet) %> |
  <%= link_to "Back to user agrovets", user_agrovets_path %>

  <%= button_to "Destroy this user agrovet", @user_agrovet, method: :delete %>
</div>