config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  } do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
  resources :orders do
    member do
      get 'orderdetail'
    end
  end
  resources :data_entries
  resources :user_agrovets
  resources :agrovets do
    resources :orders, only: [:index, :show, :new, :create]
    member do
      get 'agrovetinfo'
      get 'placeorder'
      get 'allorders'
    end
    get 'data_entries/new'
    get 'orders/new'
  end
  resources :products
  # devise_for :users
  root "pages#home"
  get 'products/index'
  get 'agrovets/index'
  get 'admin', to: 'pages#admin', as: 'pages_admin'
  get 'salesrep', to: 'pages#salesrep', as: 'pages_salesrep'
  get 'manager', to: 'pages#manager', as: 'pages_manager'
  get 'pendingorders', to: 'pages#pendingorders', as: 'pages_pendingorders'
  get 'dispatchedorders', to: 'pages#dispatchedorders', as: 'pages_dispatchedorders'
  get 'receivedorders', to: 'pages#receivedorders', as: 'pages_receivedorders'
  get 'allsalesreps', to: 'pages#allsalesreps', as: 'pages_allsalesreps'
  get 'allagrovets', to: 'pages#allagrovets', as: 'pages_allagrovets'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :agrovet
  has_one :user, through: :agrovet
  has_many :products, through: :agrovet

  STATUSES = %w[Pending Dispatched Received]

  validates :status, inclusion: { in: STATUSES }

  def humanize
    status.humanize
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[show edit update destroy]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
    @products = Product.all
    @agrovet = Agrovet.find(params[:agrovet_id])
  end

  # GET /orders/1 or /orders/1.json
  def show
    @products = Product.all
    @order = Order.find(params[:id]) # Find the order by its ID
    @agrovet = @order.agrovet
    @product_1_order_total = (@products.first&.price || 0) * (@order&.product_1_quantity || 0)
    @product_2_order_total = (@products.second&.price || 0) * (@order&.product_2_quantity || 0)
    @product_3_order_total = (@products.third&.price || 0) * (@order&.product_3_quantity || 0)
    @product_4_order_total = (@products.fourth&.price || 0) * (@order&.product_4_quantity || 0)
    @total_order_amount = @product_1_order_total + @product_2_order_total + @product_3_order_total + @product_4_order_total
  end

  # GET /orders/new
  def new
    @agrovet = Agrovet.find(params[:agrovet_id])
    @order = Order.new
    @products = Product.all
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
    @agrovet = @order.agrovet
    @products = Product.all
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)
    @agrovet = Agrovet.find(params[:order][:agrovet_id]) # Retrieve the associated agrovet
    @order = @agrovet.orders.build(order_params.except(:data_entry))
    @order.order_number = @order.id
    @products = Product.all
    @products = @agrovet.products

    respond_to do |format|
      if @order.save
        format.html { redirect_to placeorder_agrovet_path(@agrovet), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    @order = Order.find(params[:id])
    @agrovet = @order.agrovet
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to placeorder_agrovet_path(@agrovet), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def orderdetail
    @agrovet = Agrovet.find(params[:id])
    @orders = @agrovet.orders
    # @order = Order.find(params[:id])
    @order = @orders.find(params[:order_id])
    @products = Product.all
  end

  def total_amount
    # Calculate the total amount for this order
    total = 0

    total += @product_1_quantity * @products.first&.price
    total += @product_2_quantity * @products.second&.price
    total += @product_3_quantity * @products.third&.price
    total += @product_4_quantity * @products.fourth&.price

    return total
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def order_params
    params.require(:order).permit(:agrovet_id, :order_number, :product_1_quantity, :product_2_quantity,
                                  :product_3_quantity, :product_4_quantity, :status)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.hidden_field :agrovet_id, value: @agrovet.id %>
  </div>

  <div class="mb-3">
    <%= form.label :order_number, style: "display: block", class: "form-label" %>
    <%= form.text_field :order_number, readonly: true, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :product_1_quantity, @products.first.name, style: "display: block", class: "form-label" %>
    <%= form.number_field :product_1_quantity, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :product_2_quantity, @products.second.name, style: "display: block", class: "form-label" %>
    <%= form.number_field :product_2_quantity, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :product_3_quantity, @products.third.name, style: "display: block", class: "form-label" %>
    <%= form.number_field :product_3_quantity, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :product_4_quantity, @products.fourth.name, style: "display: block", class: "form-label" %>
    <%= form.number_field :product_4_quantity, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :total_amount, style: "display: block", class: "form-label" %>
    <%= form.number_field :total_amount, readonly: true, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :status, style: "display: block", class: "form-label" %>
    <%= form.select :status, Order::STATUSES, { include_blank: 'Select Status' }, class: "form-select" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Save Order", class: "btn btn-success" %>
  </div>
</div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id(order) %>">
  <h4>Order Details</h4>
  <table class="table table-striped">
    <tr>
      <td><strong>Agrovet:</strong></td>
      <td><%= "#{order.agrovet.name} (ID: #{order.agrovet_id})" %></td>
    </tr>
    <tr>
      <td><strong>Order Number:</strong></td>
      <td><%= order.id %></td>
    </tr>
    <tr>
      <td><strong><%= @products.first.name %>:</strong></td>
      <td><%= order.product_1_quantity %></td>
    </tr>
    <tr>
      <td><strong><%= @products.second.name %>:</strong></td>
      <td><%= order.product_2_quantity %></td>
    </tr>
    <tr>
      <td><strong><%= @products.third.name %>:</strong></td>
      <td><%= order.product_3_quantity %></td>
    </tr>
    <tr>
      <td><strong><%= @products.fourth.name %>:</strong></td>
      <td><%= order.product_4_quantity %></td>
    </tr>
    <tr>
      <td><strong>Total Amount:</strong></td>
      <td><%= @total_order_amount %> </td>
    </tr>
    <tr>
      <td><strong>Status:</strong></td>
      <td><%= order.status %></td>
    </tr>
    <tr>
      <td><strong>Created at:</strong></td>
      <td><%= order.created_at.in_time_zone("Nairobi").strftime("%d-%m-%Y at %H:%M:%S") %></td>
    </tr>
  </table>
  <%= link_to "Go Back to All Orders", allorders_agrovet_path(@order.agrovet_id), class: "btn btn-success" %>
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%# <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
  <% @orders.each do |order| %>
    <%= render order %>
    <p>
      <%= link_to "Show this order", order %>
    </p>
  <% end %>
</div>

<%= link_to "New order", new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<%# <div>
  <%= link_to "Back to orders", orders_path 
</div> %>

<div>
<button type="button" class="btn mt-4" style="background: brown;">
<i class="fa fa-chevron-circle-left" aria-hidden="true" style="color: #fff;"></i>
        <%= link_to "Latest Order ",  placeorder_agrovet_path(@agrovet), style: "color: #fff; text-decoration: none; font-weight: bold;" %>
</button>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>





<%# <% if @order.WHERE(Order.status == Received)%>
<div>
<% unless @order.status == 'Received' %>
  <%= link_to "Edit this order", edit_order_path(@order) %>
<% end %>

  
</div>