config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  } do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
  resources :orders do
    member do
      get 'orderdetail'
    end
  end
  resources :data_entries
  resources :user_agrovets
  resources :agrovets do
    resources :orders, only: [:index, :show, :new, :create]
    member do
      get 'agrovetinfo'
      get 'placeorder'
      get 'allorders'
    end
    get 'data_entries/new'
    get 'orders/new'
  end
  resources :products
  # devise_for :users
  root "pages#home"
  get 'products/index'
  get 'agrovets/index'
  get 'admin', to: 'pages#admin', as: 'pages_admin'
  get 'salesrep', to: 'pages#salesrep', as: 'pages_salesrep'
  get 'manager', to: 'pages#manager', as: 'pages_manager'
  get 'pendingorders', to: 'pages#pendingorders', as: 'pages_pendingorders'
  get 'dispatchedorders', to: 'pages#dispatchedorders', as: 'pages_dispatchedorders'
  get 'receivedorders', to: 'pages#receivedorders', as: 'pages_receivedorders'
  get 'allsalesreps', to: 'pages#allsalesreps', as: 'pages_allsalesreps'
  get 'allagrovets', to: 'pages#allagrovets', as: 'pages_allagrovets'
end

app/views/pages/home.html.erb
<img src="https://safiorganics.co.ke/wp-content/uploads/2021/07/cropped-Screen_Shot_2016-08-02_at_3.36.24_PM_fxegkb-300x60-1-1.png">
<%# <h5>Sales Monitoring App</h5> %>

<% if current_user %>
    <p>Welcome <%= current_user.firstname + ' ' + current_user.lastname %></p>
    <p>You are a <%= current_user.role %></p>
    <button type="button" class="btn btn-success">
    <%= link_to "Sales Rep home", pages_salesrep_path, style: "color: #fff; text-decoration: none; font-weight: bold;" %>
</button>
<% if current_user.admin? %>
    <p>There are <%= User.count %> users.</p>
    <button type="button" class="btn btn-success">
    <%= link_to "Admin Dashboard", pages_admin_path, style: "color: #fff; text-decoration: none; font-weight: bold;" %>
    </button>
<% end %>

<% if current_user.manager? %>
    <button type="button" class="btn btn-success">
    <%= link_to "Manager Dashboard", pages_manager_path, style: "color: #fff; text-decoration: none; font-weight: bold;" %>
    </button>
    <% end %>

    <%= link_to "Sign out", destroy_user_session_path, 'data-turbo-method': :delete %>
<% else %>
    <p>You are not signed in.</p>
    <button type="button" class="btn btn-success">
    <%= link_to "Sign up!", new_user_registration_path, style: "color: #fff; text-decoration; none; font-weight: bold;" %>
    </button>
    <button type="button" class="btn btn-success">
    <%= link_to "Sign in", new_user_session_path, style: "color: #fff; text-decoration: none; font-weight: bold;" %>
    </button>
<% end %>

app/views/pages/salesrep.html.erb
<div class="container">
    <div class="row justify-content-center">
    <div class="col-md-6">
        <div class="text-center mb-4">
        <!-- <h1>Sales Rep</h1> -->
        <% if current_user %>
            <p class="welcome-text">Welcome, <%= current_user.firstname + ' ' + current_user.lastname %></p>
            <%= link_to "Add Agrovet +", new_agrovet_path, style: "color: #097969; text-decoration: none; font-weight: bold; font-size:20px"%>
            <!-- Iterate through @agrovets and create links -->
            <% @agrovets.each do |agrovet| %>
            <div class="card agrovet-card">
                <div class="card-body">
                <h5 class="card-title"><%= agrovet.name %></h5>
                <%= link_to "Visit Agrovet", agrovetinfo_agrovet_path(agrovet), class: "btn btn-success btn-sm visit-agrovet-btn" %>
                </div>
            </div>
            <% end %>
            <%= link_to "Sign out", destroy_user_session_path, 'data-turbo-method': :delete, class: "btn btn-secondary btn-logout" %>
        <% end %>
        </div>
    </div>
    </div>
</div>